{% set git_import = "github.com/hashicorp/consul-template/version" %}
{% set name = "consul-template" %}
{% set version = "0.24.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hashicorp/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 96449a4bdf9f547dd2bed079a07941e56bbc27c1d2e841f5c4edc3b71c78ab93

build:
  number: 0
  script:
    {% set git_import = "github.com/hashicorp/consul-template/version" %}
    - go install -v -ldflags "-X {{ git_import }}.Name={{ name }} -X {{ git_import }}.GitCommit=''" .

requirements:
  build:
    - {{ compiler('go') }} 1.13

test:
  commands:
    - consul-template --version

about:
  home: https://github.com/hashicorp/consul-template
  license: MPL-2.0
  license_file: LICENSE
  summary: Consul-template is a daemon that provides a convenient way to populate values from Consul into the file system.
  description: |
    Consul-template is a daemon that provides a convenient way to populate values from 
    Consul into the file system.

    The daemon consul-template queries a Consul or Vault cluster and updates any number 
    of specified templates on the file system. As an added bonus, it can optionally run 
    arbitrary commands when the update process completes. 

  doc_url: https://github.com/hashicorp/consul-template/blob/v{{ version }}/README.md

extra:
  recipe-maintainers:
    - sodre
