appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: pVF7JEGkLyA1qeq/PVEYNpaK6g+jkvNwQtuy2ek9eUApsRKOEf06dKuiOPIWoajHN1VRuy6dMTVEzCI3S+HemoPZoy4dGsf8FTBwXgIF1fz7z9yHQ6KuMHFrPGXdjDU0+/Rp9/UWJjPi7SG8AyXvxEn7VLVDF7sB9/fE6wvVPtvIPzWX0NG+uFibOszudRlC5aFBdvkkghiunct5bSDZQwuVYloKC0jzHG8rR1oOrWoPrdBkpJHI+F8uYPbiILkelxJfljHnkdlFURvsEv9L5vOO8gFNBLLkU6cJd/ox/aOnZ1+WyNGr17TeAh7gf3QzAp1GECV8hR/8/Us3wY/RS+bY7dgtMncHjBqI2HqTA3FZvBvAjCpb9CMYqSLFRqvQsbHrLDzj2Xp9vToOHYP777eoaC3n5ynWRusvslDgzKPzb24xwMqeGaPkhWO9uSKuMGcuiKJF4fbcjeOzHl8fvkYtYmAMwOc3BI2T3s0GA/a4/9XN+jcQFlTE40Uj7wytVccmzwSUe+MCzQJKEXzXA46IpO0A7+h3nGtHQ7u0ldHbLrE/MKEorChakliqsY8hLzbKNq6JmyLZmQwyS22M4E+NyUuPxgsLK5odT65E8KIp59QEDuEG7qbxw2yNlx7p4jNzrbJBoeID/r9xECikoXOJbwxNhErtZpr2cqgXESI=}
provider:
  win: azure
bot:
  automerge: true
